<?php
// Auto-generated by clone_paginated.py
// Map: GET ?news4_page=N  ->  ./news4_page-N.html
$param = 'news4_page';

if (isset($_GET[$param])) {
	$page = max(1, intval($_GET[$param]));
	$file = __DIR__ . "/news4_page-{$page}.html";

	if (is_file($file)) {
		header('Content-Type: text/html; charset=UTF-8');
		readfile($file);
	} else {
		http_response_code(404);
		echo "Page not found (news4_page={$page})\n";
		echo "Co cac trang nay:\n";
		foreach (glob(__DIR__ . '/news4_page-*.html') as $f) {
			echo '  ' . basename($f) . "\n";
		}
	}
	exit;
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 
<html dir="ltr" lang="vi-VN" xmlns="http://www.w3.org/1999/xhtml">
<head>
 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta id="e_vb_meta_bburl" name="vb_meta_bburl" content="../../@4rum"/>

<meta name="generator" content="vBadvanced, vBulletin 4.2.2"/>
<script type="text/javascript">
//<![CDATA[
try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"52c34417f989d515b517352357153592",petok:"0816ca5c8a99e3c193de23668a4c913e8d0bc42d-1466094155-1800",zone:"astyles.org",rocket:"0",apps:{"ga_key":{"ua":"UA-26773206-1","ga_bs":"2"}},sha2test:0}];!function(a,b){a=document.createElement("script"),b=document.getElementsByTagName("script")[0],a.async=!0,a.src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=e982913d31/cloudflare.min.js",b.parentNode.insertBefore(a,b)}()}}catch(e){};
//]]>
</script>
<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26773206-1', 'astyles.org');
  ga('send', 'pageview');

</script>
<link rel="Shortcut Icon" href="../../@4rum/images/xenfovb/favi/tt.ico" type="image/x-icon"/>
<meta name="keywords" content="Astyles.Org , dien dan giao dien may tin , phong cach moi cho may tinh cua ban , fan miku , hatsune miku , miku theme for win 7, miku theme xp , miku skin , Vietsub, Engsub, Action, Adventure, Aliens ,Anthropomorphism ,Boing, Comedy ,Contemporary, Fantasy, Daily Life ,Dating Sim - Visual Novel ,Demons, Dragons, Dystopia ,Ecchi ,Erotic, Game, Fantasy ,Harem ,High School, Historical Human Enhancement, Large Breasts, magic ,Manga, Mecha, Navy, Novel, Nudity, Pantsu ,Parody ,Power Suits ,Romance ,School Life ,Sci-fi ,Seinen ,Shoujo-Ai ,Shounen ,Slapstick, Special Squads, Super Deformed ,Super Power ,Swordplay ,Thriller ,Time Travel ,Underworld ,Violence ,Violent Retribution for Accidental Infringement,Fansub, download,manga,anime,download manga,download anime,free download,free,direct download manga,direct download anime,vn,tải truyện,truyện tranh,đọc truyện,miễn ph�,vnsharing,Share All We Have,Viet and Sharing,dien dan anime manga,truyen tranh"/>
<meta name="description" content="Astyles.Org | New Style For You , Astyles.Org | Diễn Đàn Giao Diện Máy Tính, Mang Lại Những Phong Cách Đầy Chất Anime-Manga Cho Máy Tính Của Bạn Và Nhiều Những Thứ Khác Cho Bạn Chọn"/>
 
<meta property="fb:app_id" content="151662344993731"/>
<meta property="og:site_name" content="Astyles.Org"/>
<meta property="og:description" content="Astyles.Org | New Style For You , Astyles.Org | Diễn Đàn Giao Diện Máy Tính, Mang Lại Những Phong Cách Đầy Chất Anime-Manga Cho Máy Tính Của Bạn Và Nhiều Những Thứ Khác Cho Bạn Chọn"/>
<meta property="og:url" content="../../@4rum"/>
<meta property="og:type" content="website"/>
 
<script type="text/javascript">
<!--
	if (typeof YAHOO === 'undefined') // Load ALL YUI Local
	{
		document.write('<script type="text/javascript" src="../../@4rum/clientscript/yui/yuiloader-dom-event/yuiloader-dom-event.js?v=422"><\/script>');
		document.write('<script type="text/javascript" src="../../@4rum/clientscript/yui/connection/connection-min.js?v=422"><\/script>');
		var yuipath = '../../@4rum/clientscript/yui';
		var yuicombopath = '';
		var remoteyui = false;
	}
	else	// Load Rest of YUI remotely (where possible)
	{
		var yuipath = '../../@4rum/clientscript/yui';
		var yuicombopath = '';
		var remoteyui = true;
		if (!yuicombopath)
		{
			document.write('<script type="text/javascript" src="../../@4rum/clientscript/yui/connection/connection-min.js"><\/script>');
		}
	}
	var SESSIONURL = "";
	var SECURITYTOKEN = "guest";
	var IMGDIR_MISC = "../../@4rum/images/metro/blue/misc";
	var IMGDIR_BUTTON = "../../@4rum/images/metro/blue/buttons";
	var vb_disable_ajax = parseInt("0", 10);
	var SIMPLEVERSION = "422";
	var BBURL = "../../@4rum";
	var LOGGEDIN = 0 > 0 ? true : false;
	var THIS_SCRIPT = "adv_index";
	var RELPATH = "home/new";
	var PATHS = {
		forum : "",
		cms   : "",
		blog  : ""
	};
	var AJAXBASEURL = "../../";
// -->
</script>
<script type="text/javascript" src="../../@4rum/clientscript/vbulletin-core.js?v=422"></script>
<link rel="alternate" type="application/rss+xml" title="Astyles.Org | New Style For You RSS Feed" href="../../@4rum/external.php?type=RSS2"/>
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/main-rollup.css?d=1450050540"/>
<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/popupmenu-ie.css?d=1450050540" />
	<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/vbulletin-ie.css?d=1450050540" />
	<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/vbulletin-chrome-ie.css?d=1450050540" />
	<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/vbulletin-formcontrols-ie.css?d=1450050540" />
	<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/editor-ie.css?d=1450050540" />
	<![endif]-->
 
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('a.login-window').click(function() {
		
		// Getting the variable's value from a link 
		var loginBox = $(this).attr('href');

		//Fade in the Popup and add close button
		$(loginBox).fadeIn(300);
		
		//Set the center alignment padding + border
		var popMargTop = ($(loginBox).height() + 24) / 2; 
		var popMargLeft = ($(loginBox).width() + 24) / 2; 
		
		$(loginBox).css({ 
			'margin-top' : -popMargTop,
			'margin-left' : -popMargLeft
		});
		
		// Add the mask to body
		$('body').append('<div id="mask"></div>');
		$('#mask').fadeIn(300);
		
		return false;
	});
	
	// When clicking on the button close or the mask layer the popup closed
	$('a.close, #mask').live('click', function() { 
	  $('#mask , .login-popup').fadeOut(300 , function() {
		$('#mask').remove();  
	}); 
	return false;
	});
	
	$('#navbar_username').focus(function() {
		$('#navbar_username').parent().addClass('active');
	}); 
	$('#navbar_username').blur(function() {
		$('#navbar_username').parent().removeClass('active');
	}); 
	$('#navbar_password').focus(function() {
		$('#navbar_password_hint').parent().addClass('active');
	}); 
	$('#navbar_password').blur(function() {
		$('#navbar_password_hint').parent().removeClass('active');
	}); 

});
</script>
<script type="text/javascript" src="../../@4rum/tai.js"></script>
<script type="text/javascript">
function initSpoilers(context)
{
    var context = context || 'body';
    $('div.spoiler-head', $(context))
        .click(function(){
            $(this).toggleClass('unfolded');
            $(this).next('div.spoiler-body').slideToggle('fast');
        })
    ;
}

$(document).ready(function(){
    initSpoilers('body');
});
</script>
<link rel="stylesheet" type="text/css" href="../../@4rum/tai.css"/>
<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js' type='text/javascript'></script>
<script type='text/javascript'>$(function(){$(window).scroll(function(){if($(this).scrollTop()>250){$("#tophome").removeAttr("href");$("#tophome").stop().animate({height:40,opacity:1},{duration:500,queue:false})}else{$("#tophome").stop().animate({height:0,opacity:0},{duration:500,queue:false})}});$('#tophome').click(function(){$('body,html').animate({scrollTop:0},800);});});</script>
<link type="text/css" rel="stylesheet" href="../../@4rum/tsc_spoiler_code.css"/>
<script type="text/javascript" src="../../@4rum/tsc_spoiler_code.js"></script>
<link rel="stylesheet" href="../../@4rum/highslide/resize.css"/>
<script async type="text/javascript" src="../../@4rum/highslide/resize.js"></script>
 
<script type="text/javascript" src="../../@4rum/clientscript/vbulletin_lightbox.js?v=422"></script>
<title>Astyles.Org | Diễn Đàn Giao Diện Máy Tính , Phong Cách Mới Cho Máy Tính Của Bạn - New Theme</title>
 
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/additional.css?d=1450050540"/>
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/postbit.css"/>
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/lightbox.css"/>
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/poll.css"/>
<link rel="stylesheet" type="text/css" href="../../@4rum/clientscript/vbulletin_css/style00031l/adv_portal.css"/>
<script type="text/javascript">
<!--
function vba_attach_win(threadid)
{
	openWindow('../../@4rum/misc.php?do=showattachments&t=' + threadid, 480, 300);
}
-->
</script>
 
<script type="text/javascript">
/* <![CDATA[ */
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-26773206-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

(function(b){(function(a){"__CF"in b&&"DJS"in b.__CF?b.__CF.DJS.push(a):"addEventListener"in b?b.addEventListener("load",a,!1):b.attachEvent("onload",a)})(function(){"FB"in b&&"Event"in FB&&"subscribe"in FB.Event&&(FB.Event.subscribe("edge.create",function(a){_gaq.push(["_trackSocial","facebook","like",a])}),FB.Event.subscribe("edge.remove",function(a){_gaq.push(["_trackSocial","facebook","unlike",a])}),FB.Event.subscribe("message.send",function(a){_gaq.push(["_trackSocial","facebook","send",a])}));"twttr"in b&&"events"in twttr&&"bind"in twttr.events&&twttr.events.bind("tweet",function(a){if(a){var b;if(a.target&&a.target.nodeName=="IFRAME")a:{if(a=a.target.src){a=a.split("#")[0].match(/[^?=&]+=([^&]*)?/g);b=0;for(var c;c=a[b];++b)if(c.indexOf("url")===0){b=unescape(c.split("=")[1]);break a}}b=void 0}_gaq.push(["_trackSocial","twitter","tweet",b])}})})})(window);
/* ]]> */
</script>
</head>
<body>
<script type="text/javascript" src="../../popup.js"></script>
 
<script type="text/javascript"> 
    var adfly_id = 5450876; 
    var adfly_advert = 'int'; 
    var domains = ['drive.google.com', 'mediafire.com', 'ge.tt', 'mega.co.nz', 'skydrive.live.com']; 
</script>
<script src="https://cdn.adf.ly/js/link-converter.js"></script>
<link rel="stylesheet" href="../../@4rum/images/AstylesBlue14/cssmenu.css">
<div class="above_body">  
<div id="header" class="floatcontainer doc_header">
<div><a name="top" href="../../@4rum/" class="logo-image"><img src="../../LOGOAS.jpg" alt="Astyles.Org-Find Your Own Anime Style"/></a></div>
<div id="plus_menu_container">
<ul class="sky-mega-menu sky-mega-menu-anim-scale sky-mega-menu-response-to-icons">
<li>
<a href="../../home"><i class="fa fa-star"></i>Home</a>
</li>
<li>
<a href="../../@4rum"><i class="fa fa-star"></i>Forum</a>
</li>
<li>
<a href="#_"><i class="fa fa-print"></i>Windows Theme</a>
<div class="grid-container3">
<ul>
<li><a href="../../@4rum/forums/242-WIN-8-8-1"><i class="fa fa-tasks"></i>Windows 8 Theme</a></li>
<li><a href="../../@4rum/forums/108-WIN-7"><i class="fa fa-briefcase"></i>Windows 7 Theme</a></li>
<li><a href="../../@4rum/forums/109-WIN-XP"><i class="fa fa-gear"></i>Windows xp Theme</a></li>
</ul>
</div>
</li>
<li>
<a href="#_"><i class="fa fa-briefcase"></i>Music</a>
<div class="grid-container3">
<ul>
<li><a href="../../@4rum/forums/255-Anime-OSTs"><i class="fa fa-lemon-o"></i>Anime OST</a></li>
<li><a href="../../@4rum/forums/256-Japan-Music"><i class="fa fa-globe"></i>J-pop</a></li>
<li><a href="../../@4rum/forums/224-AMV"><i class="fa fa-picture-o"></i>AMV</a></li>
</ul>
</div>
</li>
<li>
<a href="../../@4rum/forums/40-Game"><i class="fa fa-edit"></i>Game</a>
<div class="grid-container3">
<ul>
<li><a href="../../@4rum/forums/231-Visual-Novel"><i class="fa fa-lemon-o"></i>Visual Novel</a></li>
<li><a href="../../@4rum/forums/203-Nhap-vai-Hanh-dong"><i class="fa fa-globe"></i>Nhập vai-Hành động</a></li>
<li><a href="../../@4rum/forums/220-Game-Gia-Lap"><i class="fa fa-picture-o"></i>Game Giả Lập</a></li>
</ul>
</div>
</li>
<li>
<a href="#"><i class="fa fa-edit"></i>Otaku Land</a>
<div class="grid-container3">
<ul>
<li><a href="../../@4rum/forums/223-Vocaloid-Land"><i class="fa fa-lemon-o"></i>Vocaloid</a></li>
<li><a href="../../@4rum/forums/247-Tin-Tuc"><i class="fa fa-lemon-o"></i>Tin Tức</a></li>
<li><a href="../../@4rum/forums/251-Miku-Fans-Club"><i class="fa fa-globe"></i>Miku Fans-Club</a></li>
<li><a href="../../@4rum/forums/249-Figures"><i class="fa fa-picture-o"></i>Figures</a></li>
</ul>
</div>
</li>
</ul>
</div>
<div id="fixed_header"> <a class="fixed_header_logo" href="../../@4rum/" target="_self"></a>
<div id="toplinks" class="toplinks">
<ul class="nouser">
<li><span class="header_register">
<a href="/@4rum/register.php" rel="nofollow"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Register</a></span></li>
<li>
<script type="text/javascript" src="../../@4rum/clientscript/vbulletin_md5.js?v=421"></script>
<form id="navbar_loginform" action="../../@4rum/login.php?do=login" method="post" onsubmit="md5hash(vb_login_password, vb_login_md5password, vb_login_md5password_utf, 0)">
<fieldset id="logindetails" class="logindetails"> <div> <div>
<input type="text" class="textbox default-value" name="vb_login_username" id="navbar_username" size="10" accesskey="u" tabindex="101" value="User Name" style="color: rgb(119, 119, 119);">
<input type="password" class="textbox" tabindex="102" name="vb_login_password" id="navbar_password" size="10" style="display: none;">
<input type="text" class="textbox default-value" tabindex="102" name="vb_login_password_hint" id="navbar_password_hint" size="10" value="Password" style="display: inline;">
<span id="fixed_header_remember" class="fixed_header_remember">
<label for="cb_cookieuser_navbar">
<input type="checkbox" name="cookieuser" value="1" id="cb_cookieuser_navbar" class="cb_cookieuser_navbar" accesskey="c" tabindex="103"> Remember Me?&nbsp;</label> </span>
<input type="submit" class="fixed_header_login_button" tabindex="104" value="Log in" title="Enter your username and password in the boxes provided to login, or click the 'register' button to create a profile for yourself." accesskey="s"> </div> </div>
</fieldset>
<input type="hidden" name="s" value="">
<input type="hidden" name="securitytoken" value="guest">
<input type="hidden" name="do" value="login"> <input type="hidden" name="vb_login_md5password"> <input type="hidden" name="vb_login_md5password_utf"> </form>
<script type="text/javascript">
			YAHOO.util.Dom.setStyle('navbar_password_hint', "display", "inline");
			YAHOO.util.Dom.setStyle('navbar_password', "display", "none");
			vB_XHTML_Ready.subscribe(function()
			{
			//
				YAHOO.util.Event.on('navbar_username', "focus", navbar_username_focus);
				YAHOO.util.Event.on('navbar_username', "blur", navbar_username_blur);
				YAHOO.util.Event.on('navbar_password_hint', "focus", navbar_password_hint);
				YAHOO.util.Event.on('navbar_password', "blur", navbar_password);
			});
			
			function navbar_username_focus(e)
			{
			//
				var textbox = YAHOO.util.Event.getTarget(e);
				if (textbox.value == 'User Name')
				{
				//
					textbox.value='';
					textbox.style.color='#000000';
				}
			}

			function navbar_username_blur(e)
			{
			//
				var textbox = YAHOO.util.Event.getTarget(e);
				if (textbox.value == '')
				{
				//
					textbox.value='User Name';
					textbox.style.color='#777777';
				}
			}
			
			function navbar_password_hint(e)
			{
			//
				var textbox = YAHOO.util.Event.getTarget(e);
				
				YAHOO.util.Dom.setStyle('navbar_password_hint', "display", "none");
				YAHOO.util.Dom.setStyle('navbar_password', "display", "inline");
				YAHOO.util.Dom.get('navbar_password').focus();
			}

			function navbar_password(e)
			{
			//
				var textbox = YAHOO.util.Event.getTarget(e);
				
				if (textbox.value == '')
				{
					YAHOO.util.Dom.setStyle('navbar_password_hint', "display", "inline");
					YAHOO.util.Dom.setStyle('navbar_password', "display", "none");
				}
			}
			</script>
</li>
 
<li id="fb_headerbox" class="hidden">
<a id="fb_loginbtn" href="#"><img src="../../@4rum/images/metro/blue/misc/facebook_login.gif" alt="The Facebook Platform"/></a>
</li>
 
</ul>
</div>
</div>
</div>
<img src="../../@4rum/images/xenfovb/logo.png" width="1px" height="355px"/>
 
 
<div class="body_wrapper">
<div id="breadcrumb" class="breadcrumb">
<ul class="floatcontainer">
<li class="navbithome"><a href="index.php" accesskey="1"><img src="../../@4rum/images/metro/blue/misc/navbit-home.png" alt="Trang chủ"/></a></li>
 
<div itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
<li class="navbit lastnavbit"><span><span itemprop="title">New Theme</span></span></li>
</div>
 
</ul>
<hr/>
</div>
 
 
 
 
 
<table align="center" cellspacing="0" cellpadding="0" width="100%">
<tr valign="top">
<td valign="top">
<div id="vba_news20"> 
<div class="collapse" style="padding-bottom: 0px;"><div class="homeicon2"></div>
<div class="headingsub">
<strong>--Theme New</strong>
</div>
<div class="vba_module blockbody" id="module20">
 
<table cellpadding="0" width="100%">
<tr>
<td valign="top" style="border:1px solid #d6d4d4;">
<div class="box_front">
<a href="../../@4rum/threads/29837-Honma-Meiko-V4-Windows-7-by-andrea_37" target="_blank"> Honma Meiko V4 Windows 7 by andrea_37</a>
</div>
<div class="box_front1">
Jun 14, 2016 - 6:22 PM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
</div>
<div class="noidungbox2">
<blockquote class="postcontent restore">
<a href="../../@4rum/threads/29837-Honma-Meiko-V4-Windows-7-by-andrea_37" target="_blank">
<img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/eyhA34X_6bcce496.jpg" border="0" alt=""/><br/>
<br/>
<div<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 1 
				
					
					<div class="box_front2">
				
				
					93 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29825-Theme-Win-7-Hyouka-by-Eldiaz7" target="_blank"> [Theme Win 7] Hyouka by Eldiaz7</a>
					</div>
					
					 <div class="box_front1">
                    Jun 13, 2016 - 6:34 AM - bởi <a href="../../@4rum/members/58832-Eldiaz7">Eldiaz7</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29825-Theme-Win-7-Hyouka-by-Eldiaz7" target="_blank">
                             <div style="text-align: center;"><img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="https://2.bp.blogspot.com/-lKa1k3sDJ3Q/VxL_UnGu23I/AAAAAAAAADQ/tgrzkN5xKf8Hua1wXruZIkM2vN96X5UpgCLcB/s1600/SS1.png" border="0" alt=""<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 1 
				
					
					<div class="box_front2">
				
				
					175 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->
 
    <table cellpadding="0" width="100%">   
        <tr>  
            <td valign="top" style="border:1px solid #d6d4d4;">   

                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29820-Patchouli-Knowledge-V3-Windows-7-by-andrea_37" target="_blank"> Patchouli Knowledge V3 Windows 7 by andrea_37</a>
					</div>
					
					 <div class="box_front1">
                    Jun 12, 2016 - 2:41 PM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29820-Patchouli-Knowledge-V3-Windows-7-by-andrea_37" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/490675351_b3211a88.jpg" border="0" alt="" /><br />
<br />
<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 4 
				
					
					<div class="box_front2">
				
				
					193 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29804-Chobits-V3-Windows-7-by-andrea_37" target="_blank"> Chobits V3 Windows 7 by andrea_37</a>
					</div>
					
					 <div class="box_front1">
                    Jun 09, 2016 - 5:19 PM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29804-Chobits-V3-Windows-7-by-andrea_37" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/525318541_40558bde.jpg" border="0" alt="" /><br />
<br />
<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 6 
				
					
					<div class="box_front2">
				
				
					271 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->
 
    <table cellpadding="0" width="100%">   
        <tr>  
            <td valign="top" style="border:1px solid #d6d4d4;">   

                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29598-Theme-Win-7-Kantai-Collection-Hamakaze" target="_blank"> [Theme Win 7] Kantai Collection - Hamakaze</a>
					</div>
					
					 <div class="box_front1">
                    May 06, 2016 - 12:53 PM - bởi <a href="../../@4rum/members/98680-Vuong-Lam">Vương Lâm</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29598-Theme-Win-7-Kantai-Collection-Hamakaze" target="_blank">
                             <div style="text-align: center;"><img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="http://i.imgur.com/8HdFpbe.png" border="0" alt="" /><br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 30 
				
					
					<div class="box_front2">
				
				
					1,612 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29575-Sousei-no-Onmyouji-Window-7-by-andrea_37" target="_blank"> Sousei no Onmyouji Window 7 by andrea_37</a>
					</div>
					
					 <div class="box_front1">
                    May 02, 2016 - 2:41 AM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29575-Sousei-no-Onmyouji-Window-7-by-andrea_37" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/584959861_a235f350.jpg" border="0" alt="" /><br />
<br />
<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 27 
				
					
					<div class="box_front2">
				
				
					1,293 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->
 
    <table cellpadding="0" width="100%">   
        <tr>  
            <td valign="top" style="border:1px solid #d6d4d4;">   

                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29475-Sakura-Miku-2016-Windows-7-by-andrea_37" target="_blank"> Sakura Miku 2016 Windows 7 by andrea_37</a>
					</div>
					
					 <div class="box_front1">
                    Apr 12, 2016 - 3:03 AM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29475-Sakura-Miku-2016-Windows-7-by-andrea_37" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/525318541_40558bde.jpg" border="0" alt="" /><br />
<br />
<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 91 
				
					
					<div class="box_front2">
				
				
					2,795 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29395-Saijaku-Muhai-no-Bahamut-Window-7-by-andrea_37" target="_blank"> Saijaku Muhai no Bahamut Window 7 by andrea_37</a>
					</div>
					
					 <div class="box_front1">
                    Mar 26, 2016 - 9:41 AM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29395-Saijaku-Muhai-no-Bahamut-Window-7-by-andrea_37" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/Izumi.Reina._Musaigen.no.Phantom.World_.full.1931669_40d9e87a.jpg" border="0" alt="" /><br />
<br />
<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 110 
				
					
					<div class="box_front2">
				
				
					3,705 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->
 
    <table cellpadding="0" width="100%">   
        <tr>  
            <td valign="top" style="border:1px solid #d6d4d4;">   

                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29359-Win7-Lisesharte-Lizsharte-Saijaku-Muhai-no-Bahamut" target="_blank"> [Win7] Lisesharte (Lizsharte) - Saijaku Muhai no Bahamut</a>
					</div>
					
					 <div class="box_front1">
                    Mar 21, 2016 - 6:15 AM - bởi <a href="../../@4rum/members/65817-vo0029">vo0029</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29359-Win7-Lisesharte-Lizsharte-Saijaku-Muhai-no-Bahamut" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="http://i.imgur.com/47M7quv.jpg" border="0" alt="" /><br />
The Scarlet War Princess!<br<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 47 
				
					
					<div class="box_front2">
				
				
					1,961 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29238-Yuki-Miku-2016-by-blackreapermiku" target="_blank"> Yuki Miku 2016 by blackreapermiku</a>
					</div>
					
					 <div class="box_front1">
                    Mar 03, 2016 - 9:45 AM - bởi <a href="../../@4rum/members/1205-andrea_37">andrea_37</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29238-Yuki-Miku-2016-by-blackreapermiku" target="_blank">
                             <img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="./pics/800190171_7f8a5252.jpg" border="0" alt="" /><br />
<br />
<div<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 156 
				
					
					<div class="box_front2">
				
				
					5,513 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->
 
    <table cellpadding="0" width="100%">   
        <tr>  
            <td valign="top" style="border:1px solid #d6d4d4;">   

                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/29206-Win-8-10-Theme-Nao-Tomori-By-Ricky" target="_blank"> [Win 8/10 Theme] Nao Tomori By Ricky</a>
					</div>
					
					 <div class="box_front1">
                    Feb 27, 2016 - 9:53 AM - bởi <a href="../../@4rum/members/63473-Rickyzs">Rickyzs</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/29206-Win-8-10-Theme-Nao-Tomori-By-Ricky" target="_blank">
                             <div style="text-align: center;"><img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="https://2.bp.blogspot.com/-X6G_dOWkqhY/Vs0nZQJeYpI/AAAAAAAAAng/FnwhB6g3Kr0/s1600/ss1.png" border="0" alt=""<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 30 
				
					
					<div class="box_front2">
				
				
					4,282 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>

<!-- END TEMPLATE: adv_portal_newsbits_more --><!-- BEGIN TEMPLATE: adv_portal_newsbits_more -->

            <td valign="top" width="50%" height= "345" style="border:1px solid #d6d4d4;">   


                          			
				 <div class="box_front">
				
                     <a href="../../@4rum/threads/28907-ThemeWIN7-Musaigen-no-Phantom-World-by-kurohtenshi" target="_blank"> [ThemeWIN7] Musaigen no Phantom World by kurohtenshi</a>
					</div>
					
					 <div class="box_front1">
                    Feb 12, 2016 - 7:48 AM - bởi <a href="../../@4rum/members/46156-kurohtenshi">kurohtenshi</a>
                </div>
				
				<div class="noidungbox2">

                    <blockquote class="postcontent restore">

   <a href="../../@4rum/threads/28907-ThemeWIN7-Musaigen-no-Phantom-World-by-kurohtenshi" target="_blank">
                             <div style="text-align: center;"><img style='border: 1px solid #DDD;;padding:0px;box-shadow: 0px 0px 9px #2C2C2C;' width=390 height=222 src="https://1.bp.blogspot.com/-3a6UhCC3e5M/Vr0nW7gy1AI/AAAAAAAAAC0/13pHsLE_Ftk/s1600/mus1.jpg" border="0" alt=""<a href="../../@4rum">.</a>
               </a>
</blockquote>
              
				</div>
				
					<div class="box_front1">
				
					<img src="../../@4rum/images/AstylesBlue14/cmt.png"> 143 
				
					
					<div class="box_front2">
				
				
					5,001 <img src="../../@4rum/images/AstylesBlue14/read.png">
				
			</div></div>



	
            </td>
 
        </tr>
    </table>

<!-- END TEMPLATE: adv_portal_newsbits_more -->
		
	</div>
</div>

<!-- END TEMPLATE: adv_portal_module_wrapper --></div>
	<script type="text/javascript">
	<!--
	vBulletin.register_control("vB_Lightbox_Container", "vba_news20", 1);
	//-->
	</script><div style="float:right;padding-top:2px; padding-bottom: 0px" class="floatcontainer"><!-- BEGIN TEMPLATE: pagenav -->
<form action="/index.php?id=new" method="get" class="pagination popupmenu nohovermenu">
<input type="hidden" name="id" value="new" />
	
		<span><a href="javascript://" class="popupctrl">Trang 1 của 229</a></span>
		
		
		
		<!-- BEGIN TEMPLATE: pagenav_curpage -->
<span class="selected"><a href="javascript://" title="Kết quả 1 đến 12 của 2,747">1</a></span>
<!-- END TEMPLATE: pagenav_curpage --><!-- BEGIN TEMPLATE: pagenav_pagelink -->
<span><a href="/index.php?id=new&amp;news4_page=2" title="Hiển thị kết quả 13 đến 24 của 2,747">2</a></span>
<!-- END TEMPLATE: pagenav_pagelink --><!-- BEGIN TEMPLATE: pagenav_pagelink -->
<span><a href="/index.php?id=new&amp;news4_page=3" title="Hiển thị kết quả 25 đến 36 của 2,747">3</a></span>
<!-- END TEMPLATE: pagenav_pagelink --><!-- BEGIN TEMPLATE: pagenav_pagelinkrel -->
<span><a href="/index.php?id=new&amp;news4_page=11" title="Hiển thị kết quả 121 đến 132 của 2,747"><!--+10-->11</a></span>
<!-- END TEMPLATE: pagenav_pagelinkrel --><!-- BEGIN TEMPLATE: pagenav_pagelinkrel -->
<span><a href="/index.php?id=new&amp;news4_page=51" title="Hiển thị kết quả 601 đến 612 của 2,747"><!--+50-->51</a></span>
<!-- END TEMPLATE: pagenav_pagelinkrel --><!-- BEGIN TEMPLATE: pagenav_pagelinkrel -->
<span><a href="/index.php?id=new&amp;news4_page=101" title="Hiển thị kết quả 1,201 đến 1,212 của 2,747"><!--+100-->101</a></span>
<!-- END TEMPLATE: pagenav_pagelinkrel -->
		
		<span class="separator">...</span>
		
		
		<span class="prev_next"><a rel="next" href="/index.php?id=new&amp;news4_page=2" title="Trang kế - Kết quả của 13 từ 24 của 2,747"><img src="../../@4rum/images/metro/blue/pagination/next-right.png" alt="Sau" /></a></span>
		
		
		<span class="first_last"><a href="/index.php?id=new&amp;news4_page=229" title="Trang cuối - Kết quả của 2,737 từ 2,747 của 2,747">Cuối<img src="../../@4rum/images/metro/blue/pagination/last-right.png" alt="Cuối" /></a></span>
		
	
	<ul class="popupbody popuphover">
		<li class="formsubmit jumptopage"><label>Chuyển đến trang <input type="text" name="page" size="4" /></label> <input type="submit" class="button" value="Đến" /></li>
	</ul>
</form>
<!-- END TEMPLATE: pagenav --></div><br /><br /><table width="100%" border="0" cellpadding="0" cellspacing="0">
<td width="50%" valign="top">

</td><td width="50%" valign="top">

</td></td></tr></table><table width="100%" border="0" cellpadding="0" cellspacing="0">
<td width="100%" valign="top"></td></tr></table>
			</td>
		
		
			<td valign="top" width="280" style="padding-left: 0px">
				<!-- BEGIN TEMPLATE: adv_portal_module_wrapper -->
<div class="collapse" style="padding-bottom: 0px;"><div class="homeicon2"></div>
	<div class="headingsub">
		<strong>--Problem</strong>
		
	</div>
	
	<div class="vba_module blockbody" id="module29">
		
			<blockquote class="postcontent blockrow restore">
				<div class="bbcode_container" style="margin: 0;">
					<a href="http://goo.gl/lr91Jo" target="_blank"><img  src="http://i.imgur.com/ioVKRZe.jpg" title="Problem" alt="Problem"></a>
				</div>
			</blockquote>
		
	</div>
</div>

<!-- END TEMPLATE: adv_portal_module_wrapper --><!-- BEGIN TEMPLATE: adv_portal_module_wrapper -->
<div class="collapse" style="padding-bottom: 0px;"><div class="homeicon2"></div>
	<div class="headingsub">
		<strong>--<a href="../../@4rum/search.php">Search Forums</a></strong>
		
	</div>
	
	<div class="vba_module blockbody" id="module10">
		
			<!-- BEGIN TEMPLATE: adv_portal_search -->
<div class="blockrow">
	<input class="textbox" name="query" size="13" type="text" /> <input type="submit" class="button" value="Đến" />
</div>
<div class="blockrow">
	&raquo; <a href="../../@4rum/search.php">Tìm nâng cao</a>
</div>
<!-- END TEMPLATE: adv_portal_search -->
		
	</div>
</div>
</form>
<!-- END TEMPLATE: adv_portal_module_wrapper -->
			</td>
		
	</tr>
</table>

<!-- BEGIN TEMPLATE: adv_portal_footer -->
<!-- Do NOT remove this copyright notice. Doing so is a violation of your user agreement! -->

<div align="center">.</div>
<!-- END TEMPLATE: adv_portal_footer --><!-- BEGIN TEMPLATE: footer -->

<div style="clear: left">
  <!-- BEGIN TEMPLATE: ad_footer_start -->

<!-- END TEMPLATE: ad_footer_start -->
  <!-- BEGIN TEMPLATE: ad_global_above_footer -->

<!-- END TEMPLATE: ad_global_above_footer -->
</div>




<div id="footer" class="floatcontainer footer">
	
	
	
	<script type="text/javascript">
	<!--
		// Main vBulletin Javascript Initialization
		vBulletin_init();
	//-->
	</script>
        
</div>
</div> <!-- closing div for body_wrapper -->


<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />





<!-- Start F Astyles.Org-->
	<div class="footerLegal">

<div class="footerLegalContent"><div class="container_f">
	<div class="pageWidth">
	<div class="pageContent">
<!--ND-->





<div id="copyright">
Theo giờ GMT +7. Bây giờ là <span class="time">11:22 PM</span>.
</div>
<br>
<div id="copyright">
<a href="../../" target="_blank">Astyles.Org New Style For You - Find Your Own Anime Style</a>
</div>
<br>
<div id="copyright">
Coppyright © 2014 By <a href="http://astyles.org" target="_blank">Astyles.Org</a>
</div>
<br>
<div id="copyright">
Email Contact : <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="6f3f071a0001081c1b0e1d5f5f572f08020e0603410c0002">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script>
</div>
<br>

<div id="copyright">
Vui Lòng Ghi Nguồn<a href="http://astyles.org" target="_blank"> Astyles.Org</a> Khi Bạn Sử Dụng Những Bài Viết Từ diễn đàn.
</div>
<div id="copyright">
Chúng tôi sẽ không chịu trách nhiệm với những bài viết do thành viên đăng tải lên diễn đàn.
</div>


<div id="copyrightlogo"> 

</div> 


</div>

<!--ENDND-->
	</div>	
</div>
</div>
	<!-- End F Astyles.Org -->
 
 

	
	


<!-- BEGIN TEMPLATE: ad_footer_end -->

<!-- END TEMPLATE: ad_footer_end --> 

	<!-- BEGIN TEMPLATE: facebook_footer -->
<div id="fb-root"></div>
<script type="text/javascript" src="../../@4rum/clientscript/vbulletin_facebook.js?v=422"></script>

<script type="text/javascript">
<!--
	loadFacebookAPI('en_US');
	function fbAsyncInit()
	{
		vBfb = new vB_Facebook({
			appid : "151662344993731",
			connected : 0,
			active : 0,
			autoreg : 1,
			feed_newthread : 1,
			feed_postreply : 1,
			feed_blogentry : 0,
			feed_blogcomment : 1,
			feed_newarticle : 1,
			feed_articlecomment : 1
		});
	}
// -->
</script>
<!-- END TEMPLATE: facebook_footer -->

</div>





  <!-- adnow-verification-code:59dc707bb2f463b40d4b72ace0a079ac -->

 <link rel="stylesheet" type="text/css" href="../../@4rum/tab/tabber.css" />
<script type="text/javascript" src="../../@4rum/tab/tabber.js"></script>






<a id="tophome" title="Scroll to Top" style="overflow: hidden;  height: 40px; opacity: 0;">Top</a>


<!-- END TEMPLATE: footer -->

</body>
</html>
<!-- END TEMPLATE: adv_portal -->